name: Pipeline

#Se configura el cuando ejecutar
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
##Defino los jobs a ejecutarse
jobs:
  ##Construye el proyecto
  build:
    runs-on: ubuntu-latest
    container:
      image: amazoncorretto:17-alpine
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      # instalacion de Maven
      - name: Install Maven
        run: apk add --no-cache maven
      # COmpilacion del proyecto
      - name: Build with JDK 17
        run: mvn clean compile